apiVersion: v1
kind: Pod
metadata:
  name: abacus-app
spec:
  initContainers:
  - name: git-sync
    image: k8s.gcr.io/git-sync:v3.0.1
    volumeMounts:
    - name: git-volumn
      mountPath: /tmp/git
    env:
    - name: GIT_SYNC_REPO
      value: "https://github.com/vunh76/udacity_cs_101.git"
    - name: GIT_SYNC_BRANCH
      value: "master"
    - name: GIT_SYNC_ONE_TIME
      value: "true"
    - name: GIT_SYNC_DEST
      value: cs101
  containers:
  - name: abacus
    image: python:3.7
    command: ["python"]
    args: ["/tmp/git/cs101/abacus.py"]
    volumeMounts:
    - name: git-volumn
      mountPath: /tmp/git
  nodeSelector:
    {}
  affinity:
    {}
  tolerations:
    []
  volumes:
  - name: git-volumn
    emptyDir: {}
